### ISSUE TITLE
op-node: flags - da-rpc, namespace-id not parsed from env

### ISSUE THREAD

**Issue by tuxcanfly** [celestiaorg/optimism#141]
The flags `da-rpc`, `namespace-id` for `op-node` are not being parsed from env variables.

**Comment by parkerjou** [comment]
I think the issue lies here: https://github.com/celestiaorg/optimism/blob/4b7b01f8b54667c19c3c641430900e8c1a2db882/op-node/service.go#L60

Instead of referencing the Value attribute of the flag directly, the flag should be parsed in the pattern of the others (via ctx.GlobalString of the flag name)

**Comment by tuxcanfly** [comment]
Thanks, yep should be fixed in #158
