### ISSUE TITLE
Incorrect setting of CELESTIA_NODE_AUTH_TOKEN in devnet-up.sh

### ISSUE THREAD

**Issue by antonio-altr** [celestiaorg/optimism#233]
In this line:
https://github.com/celestiaorg/optimism/blob/46d8e6a346cfb4581f4b616a0f463ea564e815d3/ops-bedrock/devnet-up.sh#L106

The container being referenced is `ops-bedrock-da-1`.
However, the actual container name is `ops-bedrock_da_1`.

![image](https://github.com/celestiaorg/optimism/assets/100987494/8982a1d3-0d5f-4db1-b949-9e51c5eec0d3)

**Comment by jcstein** [comment]
thanks! would you like to make a PR to fix this?
