### ISSUE TITLE
op-node in testnet cannot start due to missing required parameter

### ISSUE THREAD

**Issue by antonio-altr** [celestiaorg/optimism#235]
During `make testnet-up` I get this error:
```
$ docker logs ops-bedrock_op-node_1
t=2023-10-30T07:26:51+0000 lvl=info msg="Initializing Rollup Node"
t=2023-10-30T07:26:51+0000 lvl=eror msg="Unable to create the rollup node config" error="flag auth-token is required"
t=2023-10-30T07:26:51+0000 lvl=crit msg="Application failed"       message="flag auth-token is required"
```

I remedy this by adding `--auth-token=""`.

Note:
For devnet mode, auth-token is set to `$CELESTIA_NODE_AUTH_TOKEN`.
I assume for testnet mode the celestia light client node is accessible without an auth token.

**Comment by tuxcanfly** [comment]
Fixed in #254 as flag is no longer required.
