### ISSUE TITLE
batcher: concurrent batch submission

### ISSUE THREAD

**Issue by tuxcanfly** [celestiaorg/optimism#26]
If I'm not wrong celestia cannot handle concurrent transactions right now (`account sequence mismatch`) which is required for concurrent batch submission introduced in the latest optimsim `develop` branch.

We need to find a workaround for this by either disabling concurrent batch submission or locking the client so that it only submits celestia transactions in sequence.

**Comment by tuxcanfly** [comment]
Can try this with reusing nonce management code from `txmgr.go`

**Comment by evan-forbes** [comment]
the sdk relies heavily on users being able to combine sdk.Msgs into a single tx, as the mempool keeps track of its own state, where nonces are incremented, but the rpc doesn't respond with that state, resulting in mismatched nonces and failed txs.

if we keep track of the nonces ourselves, we can manually incrememt the nonces of the txs before sending them.

however we do not have the ability to send multiple PFBs in a single tx. We can however get the same functionality by sending multiple blobs per PFB. 

we can also combine the batches into a single blob and post that

**Comment by jcstein** [comment]
is this still an open issue @tuxcanfly?

**Comment by tuxcanfly** [comment]
This is not an issue, it seems like the concurrent submission was happening due a bug in Optimism `develop`, which was later fixed.
