### ISSUE TITLE
celestia blob submission failed

### ISSUE THREAD

**Issue by iavl** [celestiaorg/optimism#344]
Hi, I was building optimism locally, and using ghcr.io/rollkit/celestia-da:cce6802 for light node，the` incorrect account sequence` error for op-batcher  usually occurs after about 1 day, and restarting da does not solve it. 

logs of op-batcher:

```
t=2024-02-05T19:19:05+0000 lvl=info msg="celestia: blob submission failed; falling back to eth" err="rpc error: code = Unknown desc = : incorrect account sequence"
```

**Comment by tuxcanfly** [comment]
@iavl is there an error before this? Usually this happens because a transaction with the same nonce is already in the mempool.

**Comment by iavl** [comment]
> @iavl is there an error before this? Usually this happens because a transaction with the same nonce is already in the mempool.

There were no other errors before this. I was using mocha testnet, and this problem occurred about 1 day after the rollkit/celestia-da light node was started.

I can solve this problem by manually sending the transaction override sequence, but the same problem still occurs after running for a period of time.
