### ISSUE TITLE
question about gasPrice

### ISSUE THREAD

**Issue by iavl** [celestiaorg/optimism#373]
Hi, 

I found that in the [code repository](https://github.com/celestiaorg/optimism/blob/68e0eeed2752479de0fa0f2b68b8a742c6d42d23/op-batcher/batcher/driver.go#L348C63-L348C65), op-batcher submits blob transactions to Celestia with a fixed gasPrice -1.
Would dynamically fetching the network's gasPrice be a better solution? 
Additionally, should there be a retry mechanism for submitting blob transactions to prevent a situation where transactions remain pending due to network congestion, consequently preventing subsequent blob transactions from being confirmed?

**Comment by tuxcanfly** [comment]
Gas estimation will be supported in app https://github.com/celestiaorg/celestia-app/issues/3114

Until then yes we can implemnent a retry mechanism. Other clients such as rollkit have implemented this.
