### ISSUE TITLE
Add `DaConfig` and other changes to `op-program` 

### ISSUE THREAD

**Issue by Ferret-san** [celestiaorg/optimism#40]
While it is not currently being used, `op-program` does not have the necessary changes to incorporate an external DA source such as Celestia, for example, the [`NewDriver`](https://github.com/celestiaorg/optimism/blob/celestia-develop/op-program/client/driver/driver.go#L37) function has no parameter for the `DAConfig` that should be passed to the derivation pipeline.

Additionally, adding a function parameter is not enough, as the other part of the `op-program` that calls `NewDriver` will need to somehow pass some DA config to it, and the rest of `op-program` will very likely need a way to read data from the DA source.

**Comment by tuxcanfly** [comment]
Closed as `DAConfig` was removed in #254
