### ISSUE TITLE
Broken README link

### ISSUE THREAD

**Issue by MSevey** [celestiaorg/optimism#51]
>If you're looking to run the OP Stack + Celestia setup for this repository, please visit the [Optimism & Celestia guides and tutorials](https://docs.celestia.org/developers/intro-to-op-stack/) to get started.

This link doesn't work.

**Comment by jcstein** [comment]
The link isn't live yet, because I still need reviews on https://github.com/celestiaorg/docs/pull/753

**Comment by jcstein** [comment]
Preview available at https://docs.celestia.org/pr-preview/pr-753/developers/intro-to-op-stack/
