### ISSUE TITLE
OP proposer is stalled for 25k blocks in devnet version v0.1.0-OP_v1.0.6-CN_v0.9.5 on devnet

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/optimism#54]
The "safe" block is 25000 blocks behind the "latest" block.

[Here are the full logs](https://github.com/jcstein/logs/blob/main/115k-devnet-logs.log)

<img width="1822" alt="Screenshot 2023-05-22 at 12 04 11 PM" src="https://github.com/celestiaorg/optimism/assets/46639943/bc08d50b-3fc9-4f8d-8d27-fe7e7eeea52b">
<img width="1822" alt="Screenshot 2023-05-22 at 12 04 05 PM" src="https://github.com/celestiaorg/optimism/assets/46639943/60eca479-223a-41b4-b07b-49d788a92c4b">

**Comment by parkerjou** [comment]
Think this has to do with the speed of the derivation pipeline in op-node. Think it's quite slow to sync call_data transactions so the safe blocks tend to lag behind

**Comment by jcstein** [comment]
Thank you @TheAppleTucker - do you think even 25k blocks behind is expected based on the config?

**Comment by tuxcanfly** [comment]
there seem to have been a lot of panics in the logs above:

`grep panic 115k-devnet-logs.log`

This should be fixed by https://github.com/celestiaorg/celestia-node/issues/2244

So we should test this again against `v0.10.2`

**Comment by jcstein** [comment]
Fortunately, there were no instances of panic in this run on v0.10.1 last week https://github.com/celestiaorg/optimism/pull/120#issuecomment-1565006062

**Comment by jcstein** [comment]
unfortunately, the proposer is still stalling, but we don't really know which error thrown is the issue

**Comment by tuxcanfly** [comment]
I debugged the logs mentioned in #120 

https://github.com/celestiaorg/optimism/pull/120#issuecomment-1568787281

Long shot but are we sure it was running with proposer timeout fix?

**Comment by jcstein** [comment]
yes it was running with proposer timeout fix https://github.com/celestiaorg/optimism/pull/120#issuecomment-1568795365

**Comment by tuxcanfly** [comment]
It seems that node requests stall whenever `head request to trusted peer failed` error occurs:

https://github.com/celestiaorg/celestia-node/issues/2241#issuecomment-1568832240

This seems to be happening in node and then spilling over to proposer, will need to investigate if bumping node timeout is a workaround for this.

**Comment by tuxcanfly** [comment]
OK, I think I found the issue, it seems that proposer is stalling waiting for safe l2 head to be ahead of the checkpoint head, but since proposer was not able to update safe head due to op-node error, it can't progress and goes into a livelock.

If this is indeed the bug, then either increasing the op-node timeout or setting `OP_PROPOSER_ALLOW_NON_FINALIZED: "false"` should fix the issue.
